channels:
  - pytorch
  - conda-forge
dependencies:
  - cpuonly
  - pytorch
  - numba
  - numpy>=1.20
  - pip
  - pip:
    - tianshou
    - pettingzoo
    - sphinx<7
    - sphinx-autobuild
    - sphinxcontrib-bibtex
    - sphinxcontrib-spelling>=8.0.0, <9.0.0
    - sphinx_rtd_theme>=0.5.1
    - tensorboard
    - tqdm
    - protobuf
    - wandb~=0.12.0
